name = "mapposter"
compatibility_date = "2024-09-23"
main = "./.wrangler/functions/index.js"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "PROXY_CACHE"
id = "f07274bb1e7342518ab07fa4573f1ec2"
